events {}

http {
    server {
        listen 80;

        client_max_body_size 20M;

        # =========================
        # BACKEND API (Symfony)
        # =========================
        location ^~ /api {
            root /var/www/html/public;
            try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
            root /var/www/html/public;
            include fastcgi_params;
            fastcgi_pass webgame-backend:9000;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            fastcgi_param DOCUMENT_ROOT /var/www/html/public;
            internal;
        }

        # =========================
        # FRONTEND (Vite dev)
        # =========================
        location / {
            proxy_pass http://webgame-frontend:5173;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        # =========================
        # VITE HMR
        # =========================
        location /hmr {
            proxy_pass http://webgame-frontend:7002;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}
